# Generated by Django 5.2.5 on 2025-08-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_receipt_url_transaction_receipt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt_url',
        ),
    ]
