# Generated by Django 5.2.4 on 2025-08-01 13:05

from django.db import migrations


def create_default_roles(apps, schema_editor):
    Role = apps.get_model('authservice', 'Role')
    Role.objects.get_or_create(role='user')
    Role.objects.get_or_create(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
